site_name: Ungeniuses
site_description: Ungeniuses developer org wiki
docs_dir: docs

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/members.js

nav:
  - Home: index.md
  - Projects: projects/index.md
  - Members: members/index.md
